# Generated by Django 4.2.2 on 2023-07-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
